### ISSUE TITLE
Profile Parser Error

### ISSUE THREAD

**Issue by LAJ-47FC9** [ComaToes/ftl-profile-editor#2]
04000000060000000c0000004143485f534543544f525f35000000000c000000
4143485f534543544f525f38000000000e0000004143485f554e4c4f434b5f41
4c4c01000000150000004143485f554e495445445f46454445524154494f4e00
000000100000004143485f46554c4c5f415253454e414c000000000e00000041
43485f544f5547485f5348495000000000010000000100000001000000010000
0001000000010000000100000001000000010000000000000000000000000000
00010000000c0000004653562044616564616c75730f000000504c415945525f
534849505f46454469130000080000000000000001000000010000000c000000
4653562044616564616c75730f000000504c415945525f534849505f46454469
130000080000000000000001000000330000004100000086000000a200000031
0a0000730b0000070000000b0000000200000000000000110000000700000048
65726d696f6404000000656e67690100000005000000050000005465796c6106
0000006d616e74697301000000ef0000000800000043616c6477656c6c050000
0068756d616e01000000850000000800000043616c6477656c6c050000006875
6d616e01000000020000000800000043616c6477656c6c0500000068756d616e
01000000

**Comment by ComaToes** [comment]
Thanks for submitting the bug report. I've put a fix into v9 so you should be ok now.
