### ISSUE TITLE
Bug Report on Open Save

### ISSUE THREAD

**Issue by GingerTache** [ComaToes/ftl-profile-editor#3]
FTL Profile Editor has detected that it cannot interpret your profile correctly. Using this app may result in loss of stats/achievements.  Please copy (Ctrl-A, Ctrl-C) the following text and paste it into a new bug report here (GitHub signup is free) or post to the FLT forums here (Signup also free). If using GitHub, set the issue title as "Profile Parser Error"  I will fix the problem and release a new version as soon as I can :)  
04000000040000000c0000004143485f534543544f525f35000000000c000000
4143485f534543544f525f38000000000d0000004143485f4e4f5f5245504149
52000000000d0000004143485f4e4f5f44524f4e455300000000010000000000
0000000000000100000000000000000000000000000000000000000000000000
00000000000000000000050000000b000000546865204b65737472656c100000
00504c415945525f534849505f484152445e0600000800000000000000010000
000b000000546865204b65737472656c10000000504c415945525f534849505f
48415244380600000600000000000000010000000900000054686520546f7275
7312000000504c415945525f534849505f434952434c456e0500000500000000
000000010000000b000000546865204b65737472656c10000000504c41594552
5f534849505f48415244b00100000200000000000000010000000b0000005468
65204b65737472656c10000000504c415945525f534849505f48415244840000
00010000000000000001000000060000000b000000546865204b65737472656c
10000000504c415945525f534849505f484152445e0600000800000000000000
010000000b000000546865204b65737472656c10000000504c415945525f5348
49505f48415244380600000600000000000000010000000b000000546865204b
65737472656c10000000504c415945525f534849505f48415244b00100000200
000000000000010000000b000000546865204b65737472656c10000000504c41
5945525f534849505f4841524484000000010000000000000001000000090000
0054686520546f72757312000000504c415945525f534849505f434952434c45
6e0500000500000000000000010000000900000054686520546f727573120000
00504c415945525f534849505f434952434c455e000000010000000000000001
000000100000003f0000003e000000da000000020300009f0a00000800000024
00000007000000000000000f0000000900000044722e204a6f6e657304000000
656e676901000000050000000b00000049686c61792043617269730500000068
756d616e010000003f00000006000000536f706869610500000068756d616e00
0000003d00000006000000536f706869610500000068756d616e000000000200
000007000000537461726765720500000068756d616e01000000

**Comment by ComaToes** [comment]
This profile opens correctly with the latest version (v10). Please update and try again.
